name: PC Defenders Deployed Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKERHUB_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_SECRET }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        echo "TAG=`date +%Y.%m.%d.%H.%M.%S`" >> $GITHUB_ENV
    - name: Build the Docker image
      working-directory: ./pc-defenders-deployed
      run: |
        docker build . --file Dockerfile --tag jtb75/pc-defenders-deployed:$TAG --tag jtb75/pc-defenders-deployed:latest
    - name: Scan the Docker Image
      working-directory: ./pc-defenders-deployed
      run: |
        curl -X GET -u ${{ secrets.PCC_USER }}:${{ secrets.PCC_SECRET }} ${{ secrets.PCC_CONSOLE_URL }}/api/v1/util/twistcli > twistcli; chmod a+x twistcli;
        ./twistcli images scan -u ${{ secrets.PCC_USER }} -p ${{ secrets.PCC_SECRET }} --address ${{ secrets.PCC_CONSOLE_URL }} --details jtb75/pc-defenders-deployed:$TAG
    - name: Push the Docker image
      run: |
        docker push jtb75/pc-defenders-deployed:$TAG
        docker push jtb75/pc-defenders-deployed:latest
